import type { AuthLocalization } from "@daveyplate/better-auth-ui";

export const authLocalizationPtBR: Partial<AuthLocalization> = {
  ACCOUNT: "Conta",
  ACCOUNTS: "Contas",
  ACCOUNTS_DESCRIPTION: "Alterne entre suas contas conectadas.",
  ACCOUNTS_INSTRUCTIONS: "Entre com uma conta adicional.",
  ADD_ACCOUNT: "Adicionar Conta",
  ADD_PASSKEY: "Adicionar Chave de Acesso",
  ALREADY_HAVE_AN_ACCOUNT: "Já tem uma conta?",
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION: "Clique no avatar para enviar uma imagem personalizada.",
  AVATAR_INSTRUCTIONS: "O avatar é opcional, mas recomendado.",
  BACKUP_CODE_REQUIRED: "Código de backup é obrigatório",
  BACKUP_CODES: "Códigos de Backup",
  BACKUP_CODES_DESCRIPTION: "Guarde estes códigos em um local seguro.",
  BACKUP_CODE_PLACEHOLDER: "Código de Backup",
  BACKUP_CODE: "Código de Backup",
  CANCEL: "Cancelar",
  CHANGE_PASSWORD: "Alterar Senha",
  CHANGE_PASSWORD_DESCRIPTION: "Digite sua senha atual e a nova senha.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Use no mínimo 8 caracteres.",
  CHANGE_PASSWORD_SUCCESS: "Sua senha foi alterada.",
  CONFIRM_PASSWORD: "Confirmar Senha",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar Senha",
  CONFIRM_PASSWORD_REQUIRED: "Confirmação de senha é obrigatória",
  CONTINUE_WITH_AUTHENTICATOR: "Continuar com Autenticador",
  COPIED_TO_CLIPBOARD: "Copiado para a área de transferência",
  COPY_TO_CLIPBOARD: "Copiar para a área de transferência",
  COPY_ALL_CODES: "Copiar todos os códigos",
  CONTINUE: "Continuar",
  CURRENT_PASSWORD: "Senha Atual",
  CURRENT_PASSWORD_PLACEHOLDER: "Senha Atual",
  CURRENT_SESSION: "Sessão Atual",
  UPDATE: "Atualizar",
  DELETE: "Excluir",
  DELETE_AVATAR: "Excluir Avatar",
  DELETE_ACCOUNT: "Excluir Conta",
  DELETE_ACCOUNT_DESCRIPTION: "Remova permanentemente sua conta e todo o seu conteúdo. Esta ação não pode ser desfeita.",
  DELETE_ACCOUNT_INSTRUCTIONS: "Confirme a exclusão da sua conta. Esta ação não pode ser desfeita.",
  DELETE_ACCOUNT_VERIFY: "Verifique seu e-mail para confirmar a exclusão da conta.",
  DELETE_ACCOUNT_SUCCESS: "Sua conta foi excluída.",
  DISABLE_TWO_FACTOR: "Desativar Dois Fatores",
  DISABLED_CREDENTIALS_DESCRIPTION: "Escolha um provedor para entrar na sua conta",
  DONT_HAVE_AN_ACCOUNT: "Não tem uma conta?",
  DONE: "Concluído",
  EMAIL: "E-mail",
  EMAIL_DESCRIPTION: "Digite o endereço de e-mail que deseja usar para entrar.",
  EMAIL_INSTRUCTIONS: "Por favor, insira um endereço de e-mail válido.",
  EMAIL_IS_THE_SAME: "O e-mail é o mesmo",
  EMAIL_PLACEHOLDER: "exemplo@email.com",
  EMAIL_REQUIRED: "E-mail é obrigatório",
  EMAIL_VERIFY_CHANGE: "Verifique seu e-mail para confirmar a alteração.",
  EMAIL_VERIFICATION: "Verificação de E-mail",
  EMAIL_VERIFICATION_DESCRIPTION: "Verifique seu e-mail para obter o código de verificação.",
  EMAIL_VERIFICATION_SUCCESS: "E-mail verificado com sucesso.",
  ENABLE_TWO_FACTOR: "Ativar Dois Fatores",
  IS_INVALID: "é inválido",
  IS_REQUIRED: "é obrigatório",
  IS_THE_SAME: "é o mesmo",
  FORGOT_AUTHENTICATOR: "Esqueceu o autenticador?",
  FORGOT_PASSWORD: "Esqueci a Senha",
  FORGOT_PASSWORD_ACTION: "Enviar link de redefinição",
  FORGOT_PASSWORD_DESCRIPTION: "Digite seu e-mail para redefinir sua senha",
  FORGOT_PASSWORD_EMAIL: "Verifique seu e-mail para o link de redefinição.",
  FORGOT_PASSWORD_LINK: "Esqueceu sua senha?",
  LINK: "Vincular",
  MAGIC_LINK: "Link Mágico",
  MAGIC_LINK_ACTION: "Enviar link mágico",
  MAGIC_LINK_DESCRIPTION: "Digite seu e-mail para receber um link mágico",
  MAGIC_LINK_EMAIL: "Verifique seu e-mail pelo link mágico",
  NAME: "Nome",
  NAME_DESCRIPTION: "Digite seu nome completo ou um nome de exibição.",
  NAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  NAME_PLACEHOLDER: "Nome",
  NEW_PASSWORD: "Nova Senha",
  NEW_PASSWORD_PLACEHOLDER: "Nova Senha",
  NEW_PASSWORD_REQUIRED: "Nova senha é obrigatória",
  OR_CONTINUE_WITH: "Ou continue com",
  PASSWORD: "Senha",
  PASSWORD_PLACEHOLDER: "Senha",
  PASSWORD_REQUIRED: "Senha é obrigatória",
  PASSWORDS_DO_NOT_MATCH: "As senhas não coincidem",
  PROVIDERS: "Provedores",
  PROVIDERS_DESCRIPTION: "Conecte sua conta com um serviço de terceiros.",
  RECOVER_ACCOUNT: "Recuperar Conta",
  RECOVER_ACCOUNT_ACTION: "Recuperar conta",
  RECOVER_ACCOUNT_DESCRIPTION: "Digite um código de backup para acessar sua conta",
  REMEMBER_ME: "Lembrar de mim",
  RESEND_CODE: "Reenviar código",
  RESEND_VERIFICATION_EMAIL: "Reenviar E-mail de Verificação",
  RESET_PASSWORD: "Redefinir Senha",
  RESET_PASSWORD_ACTION: "Salvar nova senha",
  RESET_PASSWORD_DESCRIPTION: "Digite sua nova senha abaixo",
  RESET_PASSWORD_SUCCESS: "Senha redefinida com sucesso",
  REQUEST_FAILED: "Solicitação falhou",
  REVOKE: "Revogar",
  SIGN_IN: "Entrar",
  SIGN_IN_ACTION: "Entrar",
  SIGN_IN_DESCRIPTION: "Digite seu e-mail abaixo para entrar na sua conta",
  SIGN_IN_WITH: "Entrar com",
  SIGN_OUT: "Sair",
  SIGN_UP: "Criar Conta",
  SIGN_UP_ACTION: "Criar uma conta",
  SIGN_UP_DESCRIPTION: "Preencha as informações abaixo para criar sua conta",
  SIGN_UP_EMAIL: "Verifique seu e-mail pelo link de verificação.",
  SESSIONS: "Sessões",
  SESSIONS_DESCRIPTION: "Gerencie suas sessões ativas e revogue acessos.",
  SET_PASSWORD: "Definir Senha",
  SET_PASSWORD_DESCRIPTION: "Clique no botão abaixo para receber um e-mail para definir sua senha.",
  SETTINGS: "Configurações",
  SAVE: "Salvar",
  SECURITY: "Segurança",
  SWITCH_ACCOUNT: "Trocar Conta",
  TRUST_DEVICE: "Confiar neste dispositivo",
  TWO_FACTOR: "Dois Fatores",
  TWO_FACTOR_ACTION: "Verificar código",
  TWO_FACTOR_DESCRIPTION: "Digite sua senha de uso único para continuar",
  TWO_FACTOR_CARD_DESCRIPTION: "Adicione uma camada extra de segurança à sua conta.",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Digite sua senha para desativar a autenticação de dois fatores.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Digite sua senha para ativar a autenticação de dois fatores.",
  TWO_FACTOR_ENABLED: "Autenticação de dois fatores ativada",
  TWO_FACTOR_DISABLED: "Autenticação de dois fatores desativada",
  TWO_FACTOR_PROMPT: "Autenticação de Dois Fatores",
  TWO_FACTOR_TOTP_LABEL: "Escaneie o QR Code com seu Autenticador",
  SEND_VERIFICATION_CODE: "Enviar código de verificação",
  UNLINK: "Desvincular",
  UPDATED_SUCCESSFULLY: "atualizado com sucesso",
  USERNAME: "Nome de usuário",
  USERNAME_DESCRIPTION: "Digite o nome de usuário que deseja usar para entrar.",
  USERNAME_INSTRUCTIONS: "Use no máximo 32 caracteres.",
  USERNAME_PLACEHOLDER: "Nome de usuário",
  OPTIONAL_BRACKETS: "(Opcional)",
  VERIFY_YOUR_EMAIL: "Verifique seu E-mail",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Verifique seu endereço de e-mail. Acesse sua caixa de entrada e clique no link de verificação.",
  GO_BACK: "Voltar",
  SESSION_NOT_FRESH: "Sua sessão expirou. Por favor, entre novamente.",
  UPLOAD_AVATAR: "Enviar Avatar",
  UPLOAD: "Enviar",
  PRIVACY_POLICY: "Política de Privacidade",
  TERMS_OF_SERVICE: "Termos de Serviço",
  BY_CONTINUING_YOU_AGREE: "Ao continuar, você concorda com os",
};

export const authLocalizationEs: Partial<AuthLocalization> = {
  ACCOUNT: "Cuenta",
  ACCOUNTS: "Cuentas",
  ACCOUNTS_DESCRIPTION: "Alterna entre tus cuentas conectadas.",
  ACCOUNTS_INSTRUCTIONS: "Inicia sesión con una cuenta adicional.",
  ADD_ACCOUNT: "Agregar Cuenta",
  ADD_PASSKEY: "Agregar Llave de Acceso",
  ALREADY_HAVE_AN_ACCOUNT: "¿Ya tienes una cuenta?",
  AVATAR: "Avatar",
  AVATAR_DESCRIPTION: "Haz clic en el avatar para subir una imagen personalizada.",
  AVATAR_INSTRUCTIONS: "El avatar es opcional pero recomendado.",
  BACKUP_CODE_REQUIRED: "El código de respaldo es obligatorio",
  BACKUP_CODES: "Códigos de Respaldo",
  BACKUP_CODES_DESCRIPTION: "Guarda estos códigos en un lugar seguro.",
  BACKUP_CODE_PLACEHOLDER: "Código de Respaldo",
  BACKUP_CODE: "Código de Respaldo",
  CANCEL: "Cancelar",
  CHANGE_PASSWORD: "Cambiar Contraseña",
  CHANGE_PASSWORD_DESCRIPTION: "Ingresa tu contraseña actual y la nueva contraseña.",
  CHANGE_PASSWORD_INSTRUCTIONS: "Usa al menos 8 caracteres.",
  CHANGE_PASSWORD_SUCCESS: "Tu contraseña ha sido cambiada.",
  CONFIRM_PASSWORD: "Confirmar Contraseña",
  CONFIRM_PASSWORD_PLACEHOLDER: "Confirmar Contraseña",
  CONFIRM_PASSWORD_REQUIRED: "La confirmación de contraseña es obligatoria",
  CONTINUE_WITH_AUTHENTICATOR: "Continuar con Autenticador",
  COPIED_TO_CLIPBOARD: "Copiado al portapapeles",
  COPY_TO_CLIPBOARD: "Copiar al portapapeles",
  COPY_ALL_CODES: "Copiar todos los códigos",
  CONTINUE: "Continuar",
  CURRENT_PASSWORD: "Contraseña Actual",
  CURRENT_PASSWORD_PLACEHOLDER: "Contraseña Actual",
  CURRENT_SESSION: "Sesión Actual",
  UPDATE: "Actualizar",
  DELETE: "Eliminar",
  DELETE_AVATAR: "Eliminar Avatar",
  DELETE_ACCOUNT: "Eliminar Cuenta",
  DELETE_ACCOUNT_DESCRIPTION: "Elimina permanentemente tu cuenta y todo su contenido. Esta acción no se puede deshacer.",
  DELETE_ACCOUNT_INSTRUCTIONS: "Confirma la eliminación de tu cuenta. Esta acción no se puede deshacer.",
  DELETE_ACCOUNT_VERIFY: "Revisa tu correo para confirmar la eliminación de la cuenta.",
  DELETE_ACCOUNT_SUCCESS: "Tu cuenta ha sido eliminada.",
  DISABLE_TWO_FACTOR: "Desactivar Dos Factores",
  DISABLED_CREDENTIALS_DESCRIPTION: "Elige un proveedor para iniciar sesión en tu cuenta",
  DONT_HAVE_AN_ACCOUNT: "¿No tienes una cuenta?",
  DONE: "Listo",
  EMAIL: "Correo electrónico",
  EMAIL_DESCRIPTION: "Ingresa la dirección de correo que deseas usar para iniciar sesión.",
  EMAIL_INSTRUCTIONS: "Por favor ingresa una dirección de correo válida.",
  EMAIL_IS_THE_SAME: "El correo es el mismo",
  EMAIL_PLACEHOLDER: "ejemplo@correo.com",
  EMAIL_REQUIRED: "El correo electrónico es obligatorio",
  EMAIL_VERIFY_CHANGE: "Revisa tu correo para confirmar el cambio.",
  EMAIL_VERIFICATION: "Verificación de Correo",
  EMAIL_VERIFICATION_DESCRIPTION: "Revisa tu correo para obtener el código de verificación.",
  EMAIL_VERIFICATION_SUCCESS: "Correo verificado exitosamente.",
  ENABLE_TWO_FACTOR: "Activar Dos Factores",
  IS_INVALID: "es inválido",
  IS_REQUIRED: "es obligatorio",
  IS_THE_SAME: "es el mismo",
  FORGOT_AUTHENTICATOR: "¿Olvidaste el autenticador?",
  FORGOT_PASSWORD: "Olvidé mi Contraseña",
  FORGOT_PASSWORD_ACTION: "Enviar enlace de restablecimiento",
  FORGOT_PASSWORD_DESCRIPTION: "Ingresa tu correo para restablecer tu contraseña",
  FORGOT_PASSWORD_EMAIL: "Revisa tu correo para el enlace de restablecimiento.",
  FORGOT_PASSWORD_LINK: "¿Olvidaste tu contraseña?",
  LINK: "Vincular",
  MAGIC_LINK: "Enlace Mágico",
  MAGIC_LINK_ACTION: "Enviar enlace mágico",
  MAGIC_LINK_DESCRIPTION: "Ingresa tu correo para recibir un enlace mágico",
  MAGIC_LINK_EMAIL: "Revisa tu correo por el enlace mágico",
  NAME: "Nombre",
  NAME_DESCRIPTION: "Ingresa tu nombre completo o un nombre para mostrar.",
  NAME_INSTRUCTIONS: "Usa como máximo 32 caracteres.",
  NAME_PLACEHOLDER: "Nombre",
  NEW_PASSWORD: "Nueva Contraseña",
  NEW_PASSWORD_PLACEHOLDER: "Nueva Contraseña",
  NEW_PASSWORD_REQUIRED: "La nueva contraseña es obligatoria",
  OR_CONTINUE_WITH: "O continúa con",
  PASSWORD: "Contraseña",
  PASSWORD_PLACEHOLDER: "Contraseña",
  PASSWORD_REQUIRED: "La contraseña es obligatoria",
  PASSWORDS_DO_NOT_MATCH: "Las contraseñas no coinciden",
  PROVIDERS: "Proveedores",
  PROVIDERS_DESCRIPTION: "Conecta tu cuenta con un servicio de terceros.",
  RECOVER_ACCOUNT: "Recuperar Cuenta",
  RECOVER_ACCOUNT_ACTION: "Recuperar cuenta",
  RECOVER_ACCOUNT_DESCRIPTION: "Ingresa un código de respaldo para acceder a tu cuenta",
  REMEMBER_ME: "Recuérdame",
  RESEND_CODE: "Reenviar código",
  RESEND_VERIFICATION_EMAIL: "Reenviar Correo de Verificación",
  RESET_PASSWORD: "Restablecer Contraseña",
  RESET_PASSWORD_ACTION: "Guardar nueva contraseña",
  RESET_PASSWORD_DESCRIPTION: "Ingresa tu nueva contraseña abajo",
  RESET_PASSWORD_SUCCESS: "Contraseña restablecida exitosamente",
  REQUEST_FAILED: "Solicitud fallida",
  REVOKE: "Revocar",
  SIGN_IN: "Iniciar Sesión",
  SIGN_IN_ACTION: "Iniciar sesión",
  SIGN_IN_DESCRIPTION: "Ingresa tu correo abajo para iniciar sesión en tu cuenta",
  SIGN_IN_WITH: "Iniciar sesión con",
  SIGN_OUT: "Cerrar Sesión",
  SIGN_UP: "Crear Cuenta",
  SIGN_UP_ACTION: "Crear una cuenta",
  SIGN_UP_DESCRIPTION: "Completa la información abajo para crear tu cuenta",
  SIGN_UP_EMAIL: "Revisa tu correo por el enlace de verificación.",
  SESSIONS: "Sesiones",
  SESSIONS_DESCRIPTION: "Administra tus sesiones activas y revoca accesos.",
  SET_PASSWORD: "Establecer Contraseña",
  SET_PASSWORD_DESCRIPTION: "Haz clic en el botón para recibir un correo y establecer tu contraseña.",
  SETTINGS: "Configuración",
  SAVE: "Guardar",
  SECURITY: "Seguridad",
  SWITCH_ACCOUNT: "Cambiar Cuenta",
  TRUST_DEVICE: "Confiar en este dispositivo",
  TWO_FACTOR: "Dos Factores",
  TWO_FACTOR_ACTION: "Verificar código",
  TWO_FACTOR_DESCRIPTION: "Ingresa tu contraseña de un solo uso para continuar",
  TWO_FACTOR_CARD_DESCRIPTION: "Agrega una capa extra de seguridad a tu cuenta.",
  TWO_FACTOR_DISABLE_INSTRUCTIONS: "Ingresa tu contraseña para desactivar la autenticación de dos factores.",
  TWO_FACTOR_ENABLE_INSTRUCTIONS: "Ingresa tu contraseña para activar la autenticación de dos factores.",
  TWO_FACTOR_ENABLED: "Autenticación de dos factores activada",
  TWO_FACTOR_DISABLED: "Autenticación de dos factores desactivada",
  TWO_FACTOR_PROMPT: "Autenticación de Dos Factores",
  TWO_FACTOR_TOTP_LABEL: "Escanea el código QR con tu Autenticador",
  SEND_VERIFICATION_CODE: "Enviar código de verificación",
  UNLINK: "Desvincular",
  UPDATED_SUCCESSFULLY: "actualizado exitosamente",
  USERNAME: "Nombre de usuario",
  USERNAME_DESCRIPTION: "Ingresa el nombre de usuario que deseas usar para iniciar sesión.",
  USERNAME_INSTRUCTIONS: "Usa como máximo 32 caracteres.",
  USERNAME_PLACEHOLDER: "Nombre de usuario",
  OPTIONAL_BRACKETS: "(Opcional)",
  VERIFY_YOUR_EMAIL: "Verifica tu Correo",
  VERIFY_YOUR_EMAIL_DESCRIPTION: "Verifica tu dirección de correo. Revisa tu bandeja de entrada y haz clic en el enlace de verificación.",
  GO_BACK: "Volver",
  SESSION_NOT_FRESH: "Tu sesión expiró. Por favor inicia sesión nuevamente.",
  UPLOAD_AVATAR: "Subir Avatar",
  UPLOAD: "Subir",
  PRIVACY_POLICY: "Política de Privacidad",
  TERMS_OF_SERVICE: "Términos de Servicio",
  BY_CONTINUING_YOU_AGREE: "Al continuar, aceptas los",
};
